version: '3.8'

services:
  app:
   build:
     context: app/
   container_name: myblog_app_$BRANCH_NAME
   image: ${CONTAINER_REGISTORY_URL}myblog/app:$BRANCH_NAME
   volumes:
    - ./app/em:/home/web/em
   ports:
    - "9000:9000"
   depends_on:
    - db

   db:
    build:
       context: db/
    container_name: myblog_db_$BRANCH_NAME
    image: ${CONTAINER_REGISTORY_URL}myblog/db:$BRANCH_NAME
    volumes:
     - ./app/em:/home/web/em
    ports:
     - 5432:5432"
    environment:
      TZ:'Asia/Tokyo'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_INITID_ARGS: '--encoding=UTF-8 --locale-ja_JP.UTF-8'
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

    web:
        build:
           context: ./web
        container_name: myblog_web_$BRANCH_NAME
		image: ${CONTAINER_REGISTORY_URL}myblog/web:$BRANCH_NAME
        ports:
          - "8000:8000"
        volumes:
          - ./web/conf:/etc/nginx/conf.d
          - ./web/uwsgi_params:/etc/nginx/uwsgi_params
          - ./web/error_log/error.log:/var/log/nginx/error.log
          - ./app/boovoice/static:/home/boovoice/static
        depends_on:
          - app