# Generated by Django 4.0.1 on 2022-01-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('token_blacklist', '0011_linearizes_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('blacklistedtoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='token_blacklist.blacklistedtoken')),
            ],
            bases=('token_blacklist.blacklistedtoken',),
        ),
        migrations.CreateModel(
            name='Outstanding',
            fields=[
                ('outstandingtoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='token_blacklist.outstandingtoken')),
            ],
            bases=('token_blacklist.outstandingtoken',),
        ),
    ]
