# Generated by Django 4.0.1 on 2022-01-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outstanding',
            name='outstandingtoken_ptr',
        ),
        migrations.DeleteModel(
            name='BlacklistedToken',
        ),
        migrations.DeleteModel(
            name='Outstanding',
        ),
    ]
