# Generated by Django 4.0.1 on 2022-01-24 05:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 1, 24, 5, 52, 10, 498215, tzinfo=utc))),
                ('updated', models.DateTimeField(default=datetime.datetime(2022, 1, 24, 5, 52, 10, 498232, tzinfo=utc))),
                ('is_deleted', models.BooleanField(default=False, help_text='Mark an item deleted without actually deleting it from database. I.e, soft deletion.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft deletion date and time.', null=True)),
                ('name', models.CharField(max_length=30, verbose_name='category_name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 1, 24, 5, 52, 10, 498215, tzinfo=utc))),
                ('updated', models.DateTimeField(default=datetime.datetime(2022, 1, 24, 5, 52, 10, 498232, tzinfo=utc))),
                ('is_deleted', models.BooleanField(default=False, help_text='Mark an item deleted without actually deleting it from database. I.e, soft deletion.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft deletion date and time.', null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content', to='contents.categories')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
